### ISSUE TITLE
[BUG] Drop-in details configuration not working on version 3.3.0

### ISSUE THREAD

**Issue by emidev98** [Adyen/adyen-components-js-sample-code#12]
## Explanation

The data model returned by the [API](https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v51/paymentMethods) is not full working because the property **paymentMethods.details** does not respect any of the sent parameters. 

## Example

With the next config we should get 5 inputs one after the other one in a list:
```
{
  "paymentMethods": [
    {
      "brands": [
        "mc",
        "visa"
      ],
      "details": [
        {
          "key": "number",
          "type": "text"
        },
        {
          "key": "expiryMonth",
          "type": "text"
        },
        {
          "key": "expiryYear",
          "type": "text"
        },
        {
          "key": "cvc",
          "type": "text"
        },
        {
          "key": "holderName",
          "optional": true,
          "type": "text"
        }
      ],
      "name": "Credit Card",
      "type": "scheme"
    }
  ]
}
```
But we are getting the default configuration of the credit card drop-in (yes styles are different because we overwrite them):

![image](https://user-images.githubusercontent.com/49301655/70435970-8526ac00-1a88-11ea-945c-66a2ec2c1437.png)

**Comment by marcperez** [comment]
Hi @emidev98,

The Card Component rendering does not depend on the `details` property of the API `/paymentMethods` response.

Please, check the [Card Component documentation](https://docs.adyen.com/payment-methods/cards/web-component#show-the-available-cards-in-your-payment-form) in order to configure which fields you wish to display.

If you have any other question about our integrations, please contact our [support team](https://support.adyen.com/).

**Comment by emidev98** [comment]
Hello @marcperez, thanks so much for clarify that :)
