### ISSUE TITLE
Missing documentation for klarna paymentMethodsConfiguration

### ISSUE THREAD

**Issue by LucianDavies** [Adyen/adyen-components-js-sample-code#3]
Is there documentation for paymentMethodsConfiguration especially the klarna component. The demo has the country greyed out meaning we cant demo test it and also it would be nice to know if we can pre-fill some of the values on dropin initialisation.

this page says nothing about klarna
https://docs.adyen.com/checkout/components-web/#supported-payment-methods

**Comment by pabloai** [comment]
Hi Lucian,

In the `paymentMethodsConfiguration` you can pass any configuration you would pass to separate Components.

In the case of Klarna, it's not in the list because the Component you are referring to is for the old integration. The new integration is supported in more countries and works as a redirect, therefore it doesn't have a standalone Component.

To change your account settings and use this new integration of Klarna, please contact [Adyen support](https://support.adyen.com/hc/en-us).
